In [1]:
import pandas as pd 
import numpy as np 
import os 
import shutil

In [8]:
framesFake={"Folder":[],"Frame Count":[],"File Path":[],"Label":[]}
for folder in os.listdir('dataset/full/fake'):
    countFrame=0
    for frames in os.listdir(f'dataset/full/fake/{folder}'):
        countFrame+=1
    framesFake["Folder"].append(folder)
    framesFake["Frame Count"].append(countFrame)
    framesFake['File Path'].append(f"fake/frames/{folder}")
    framesFake["Label"].append(0)

fakeFramesDF=pd.DataFrame(framesFake)
print(fakeFramesDF.shape)
fakeFramesDF.head()

(48, 4)

      Folder  Frame Count              File Path  Label
0  0000_fake          292  fake/frames/0000_fake      0
1  0001_fake          192  fake/frames/0001_fake      0
2  0002_fake          244  fake/frames/0002_fake      0
3  0003_fake          148  fake/frames/0003_fake      0
4  0005_fake          203  fake/frames/0005_fake      0

In [8]:
framesReal={"Folder":[],"Frame Count":[],"File Path":[],"Label":[]}
for folder in os.listdir('dataset/full/real'):
    countFrame=0
    for frames in os.listdir(f'dataset/full/real/{folder}'):
        countFrame+=1
    framesReal["Folder"].append(folder)
    framesReal["Frame Count"].append(countFrame)
    framesReal['File Path'].append(f"real/frames/{folder}")
    framesReal["Label"].append(1)

realFramesDF=pd.DataFrame(framesReal)
print(realFramesDF.shape)
realFramesDF.head()

(48, 4)

  Folder  Frame Count         File Path  Label
0   0000          292  real/frames/0000      1
1   0001          192  real/frames/0001      1
2   0002          244  real/frames/0002      1
3   0003          148  real/frames/0003      1
4   0005          203  real/frames/0005      1

In [12]:
print(np.sum(fakeFramesDF['Frame Count']))
print(np.sum(realFramesDF['Frame Count']))
print(np.sum(fakeFramesDF['Frame Count'])+np.sum(realFramesDF['Frame Count']))

16875
17213
34088

In [9]:
if not os.path.exists("fakeFrame.csv"):
    fakeFramesDF.to_csv("fakeFrame.csv",index=False,encoding="utf-8")
if not os.path.exists("realFrame.csv"):
    realFramesDF.to_csv("realFrame.csv",index=False,encoding="utf-8")

In [10]:
df=pd.concat([realFramesDF,fakeFramesDF],ignore_index=True)

df=df[df["Frame Count"]<32]

for path in df["File Path"]:
    if os.path.exists(path):
        shutil.rmtree(path)